version: "3"

volumes:
  frontend:

services:
  frontend:
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/:/app/
    ports:
      - "3000:3000"